server:
  port: 3344
spring:
  application:
    name: springcloud-config-server
    #连接远程的仓库
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/xinmu123456/springcloud-config.git #https

# 通过config-server 可以连接到git访问其中的资源以及配置