server:
  port: 9527
spring:
  application:
    name: springcloud-zuul

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: zuul-9527.com
    prefer-ip-address: true


# 展示的信息
info:
  app.name: xinmu-springcloud
  company.name: blog.xinmu.com

zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
  #ignored-services: springcloud-provider-dept #不能再使用这个路径访问了
  ignored-services: "*" #隐藏全部的微服务名字
  prefix: /xinmu #设置公共的访问前缀